### ISSUE TITLE
No rule to make target 'build/SDL.lo'

### ISSUE THREAD

**Issue by taylon** [revery-ui/esy-sdl2#12]
Hi,

I have been trying to compile Oni2 in ArchLinux but I keep getting the following error:

`make: *** No rule to make target 'build/SDL.lo', needed by 'build/libSDL2.la'.  Stop.`

[Here](https://pastebin.com/veSf5UDT) is the output of `esy build` which includes the output of ./configure and make.

I have everything listed [here](https://github.com/revery-ui/revery/wiki/Building-&-Installing) installed and I'm suspecting it is not a missing dependency because I'm able to compile it using cmake (the official Arch package is also built using [cmake](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/sdl2))

I'm pretty sure I'll figure it out eventually but I appreciate if anyone has any leads

**Comment by mephistopheles-8** [comment]
This may be an issue with the SDL2 `./configure` script on Linux or Arch-like distros.  The generated Makefile omits the `$(objects)` directory on a bunch of `*.lo` targets.  I could get this to build by editing the `package.json` file to use `cmake` for Linux.

**Comment by taylon** [comment]
Yeah, that is what I was about to suggest and send a PR for, although I'm not sure if that could cause issues in other distros...
